name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-windowservercore

    steps:
      - name: Checkout
        uses: actions/checkout@v3

     
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 models --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 models --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run tests
        run: |
          pytest --cov=models tests/