name: CI Build

# https://docs.github.com/en/actions
# https://github.com/actions
on:
  push:
    branches:
      - main
  pull_request:  # when a branch is merged into the main branch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ${{matrix.os}}
    #strategy:
      #matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
    container: python:3.11-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # https://github.com/actions/checkout, action.yml

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Lint with flake8 (not pylint)
        run: |
          flake8 models --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 models --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests with pytest, use verbose, produce coverage report
        run: |
          pytest -v --cov=models tests/